# This is a basic workflow that is manually triggered

name: Manual Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install deps
        run: yarn
      - name: Build App
        run: yarn build
      - name: Generate changelog
        id: changelog
        uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.github_token }}
          create-summary: true

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        if: steps.changelog.outputs.skipped != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          
      - name: upload build artifact
      
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build # or path/to/artifact

          
          
          
          
          
