name: Release Package

on: [pull_request]

jobs:
  # only publish artifact when PR was merged, not if it was closed without merging
  publish-artifact:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    permissions:
      packages: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@chris-fo'
      - run: yarn
      - run: yarn publish --out /artifacts/%s-%v.tgz
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
