name: Manual Release

on:
  workflow_dispatch:

jobs:
  build:
    if: ${{ steps.changelog.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"

      - name: Install deps
        run: yarn
      - name: Build App
        run: |
          yarn build
          tar czf build.tar.gz ./build
          zip -r build.zip ./build
          
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build.tar.gz, build.zip"
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.github_token }}
          
